# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDark.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreenDark(object):
    def setupUi(self, MainScreenDark):
        MainScreenDark.setObjectName("MainScreenDark")
        MainScreenDark.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainScreenDark)
        self.centralwidget.setObjectName("centralwidget")
        self.bgwidget = QtWidgets.QWidget(self.centralwidget)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(67, 67, 67, 255), stop:1 rgba(0, 0, 0, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 160, 301, 51))
        self.label_2.setStyleSheet("font: 11pt \"Microsoft YaHei UI\";;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));")
        self.label_2.setObjectName("label_2")
        self.Add_bot = QtWidgets.QPushButton(self.bgwidget)
        self.Add_bot.setGeometry(QtCore.QRect(250, 250, 281, 61))
        self.Add_bot.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(116, 116, 116, 255), stop:1 rgba(75, 75, 75, 255));\n"
"border-radius:20px;\n"
"font: 24pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(67, 67, 67, 255), stop:1 rgba(0, 0, 0, 255));")
        self.Add_bot.setObjectName("Add_bot")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(170, 70, 451, 61))
        self.label.setStyleSheet("font: 40pt \"Microsoft YaHei UI\";;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));")
        self.label.setObjectName("label")
        self.Done_bot = QtWidgets.QPushButton(self.bgwidget)
        self.Done_bot.setGeometry(QtCore.QRect(250, 320, 281, 61))
        self.Done_bot.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(116, 116, 116, 255), stop:1 rgba(75, 75, 75, 255));\n"
"border-radius:20px;\n"
"font: 24pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(67, 67, 67, 255), stop:1 rgba(0, 0, 0, 255));")
        self.Done_bot.setObjectName("Done_bot")
        self.num = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.num.setGeometry(QtCore.QRect(270, 200, 231, 31))
        self.num.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.num.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.num.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(116, 116, 116, 255), stop:1 rgba(75, 75, 75, 255));\n"
"border-radius:20px;\n"
"font: 10pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(67, 67, 67, 255), stop:1 rgba(0, 0, 0, 255));")
        self.num.setMaximum(240.59)
        self.num.setObjectName("num")
        self.Light_bot = QtWidgets.QPushButton(self.bgwidget)
        self.Light_bot.setGeometry(QtCore.QRect(710, 500, 81, 41))
        self.Light_bot.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(116, 116, 116, 255), stop:1 rgba(75, 75, 75, 255));\n"
"border-radius:20px;\n"
"font: 10pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(67, 67, 67, 255), stop:1 rgba(0, 0, 0, 255));")
        self.Light_bot.setObjectName("Light_bot")
        MainScreenDark.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainScreenDark)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainScreenDark.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainScreenDark)
        self.statusbar.setObjectName("statusbar")
        MainScreenDark.setStatusBar(self.statusbar)

        self.retranslateUi(MainScreenDark)
        QtCore.QMetaObject.connectSlotsByName(MainScreenDark)

    def retranslateUi(self, MainScreenDark):
        _translate = QtCore.QCoreApplication.translate
        MainScreenDark.setWindowTitle(_translate("MainScreenDark", "MainWindow"))
        self.label_2.setText(_translate("MainScreenDark", "Enter video duration ( Minutes.Seconds )"))
        self.Add_bot.setText(_translate("MainScreenDark", "Add"))
        self.label.setText(_translate("MainScreenDark", "How Many Hours"))
        self.Done_bot.setText(_translate("MainScreenDark", "Done"))
        self.Light_bot.setText(_translate("MainScreenDark", "Light Mode"))
